"""Minimal FastAPI entry-point for a containerised AI agent.

This file is intended as part of the `agent-template` cookie-cutter.  When a new
agent is generated, users will typically customise:
  • the Pydantic request/response schemas
  • the implementation inside `invoke()`

The runtime contract expected by the Agent Control Plane is:
  POST /invoke    – main inference/action endpoint
  GET  /health    – liveness probe
  GET  /metadata  – YAML metadata from `agent.yaml`
"""

from datetime import datetime
from typing import Any, Dict, List
import os, logging
from dotenv import load_dotenv
from langchain.prompts import PromptTemplate
from langchain_core.output_parsers import JsonOutputParser
from langgraph.graph import StateGraph, END
from langchain_anthropic import ChatAnthropic
try:
    from agentsystems_sdk.observability import log_thought
except ImportError:
    # Fallback no-op decorator when SDK is unavailable
    def log_thought(arg=None):
        """Simple no-op decorator compatible with @log_thought or @log_thought("name")."""
        if callable(arg):
            # Used as @log_thought
            return arg
        else:
            # Used as @log_thought("name") – return decorator
            def _decorator(fn):
                return fn
            return _decorator

import pathlib

import yaml
from fastapi import FastAPI, Request
from pydantic import BaseModel

# ── Load static metadata once at startup ──────────────────────────────────────
meta_path = pathlib.Path(__file__).with_name("agent.yaml")
if not meta_path.exists():
    raise FileNotFoundError("agent.yaml not found next to main.py – required by template")

meta: Dict[str, Any] = yaml.safe_load(meta_path.read_text())
NAME: str = meta.get("name", "UnnamedAgent")
VERSION: str = meta.get("version", "0.0.0")

app = FastAPI(title=NAME, version=VERSION)


# ── Pydantic Schemas – replace with your own ─────────────────────────────────
class InvokeRequest(BaseModel):
    date: str  # e.g. "April 1"


class InvokeResponse(BaseModel):
    thread_id: str  # UUID generated by gateway and echoed back
    date: str
    events: List[str]
    story: str
    timestamp: datetime


# ── Routes – minimal contract ────────────────────────────────────────────────
# ── Build LangGraph pipeline once at startup ────────────────────────────────
load_dotenv()
ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
if not ANTHROPIC_API_KEY:
    logging.warning("ANTHROPIC_API_KEY not set – agent will error on invoke")

# Prompt for historical events (expects VALID JSON)
_events_prompt = PromptTemplate(
    template=(
        """
        You are a helpful AI that MUST return VALID JSON ONLY. No markdown.
        Return exactly 3 historical events that occurred on this month/day: {date}

        Expected format:\n{{\n  \"events\": [ \"Event #1\", \"Event #2\", \"Event #3\" ] }}
        """
    ),
    input_variables=["date"],
)

_llm = ChatAnthropic(model="claude-3-5-sonnet-latest", api_key=ANTHROPIC_API_KEY, temperature=0)
_parser = JsonOutputParser()
_chain_events = _events_prompt | _llm | _parser

_story_prompt = PromptTemplate(
    template="""
    Compose a concise, engaging narrative (max 120 words) weaving these historical events together on {date}:
    {events}
    """,
    input_variables=["date", "events"],
)
_chain_story = _story_prompt | _llm

class _SGState(dict):
    date: str
    historical_events: List[str]
    story: str

graph = StateGraph(_SGState)

@log_thought("get_historical_events")
def get_historical_events_node(state: _SGState) -> _SGState:
    result = _chain_events.invoke({"date": state["date"]})
    state["historical_events"] = result.get("events", [])
    return state

@log_thought("story_node")
def story_node(state: _SGState) -> _SGState:
    story_result = _chain_story.invoke({"date": state["date"], "events": state["historical_events"]})
    # LangChain may return an AIMessage; extract its content if present
    if hasattr(story_result, "content"):
        story_text = story_result.content
    else:
        story_text = str(story_result)
    state["story"] = story_text
    return state

graph.add_node("events", get_historical_events_node)
graph.add_node("story_node", story_node)
graph.add_edge("events", "story_node")
graph.add_edge("story_node", END)
graph.set_entry_point("events")
_pipeline = graph.compile()


@app.post("/invoke", response_model=InvokeResponse, tags=["Agent Ops"])
async def invoke(request: Request, req: InvokeRequest) -> InvokeResponse:  # noqa: D401
    """Return three events for the given date and a short narrative."""
    thread_id = request.headers.get("X-Thread-Id", "")
    initial_state = {"date": req.date, "historical_events": []}
    final_state: _SGState = _pipeline.invoke(initial_state)  # type: ignore[arg-type]
    return InvokeResponse(
        thread_id=thread_id,
        date=req.date,
        events=final_state["historical_events"],
        story=str(final_state.get("story", "")),

        timestamp=datetime.utcnow(),
    )


@app.get("/health", tags=["Agent Ops"])
async def health() -> Dict[str, str]:
    return {"status": "ok", "version": VERSION}


@app.get("/metadata", tags=["Agent Ops"])
async def metadata() -> Dict[str, Any]:
    return meta
